baseURL = 'indoxicate.me'
languageCode = 'en-us'
title = 'Indoxicate'
paginate = 3
theme = 'maverick'


[permalinks]
  posts = ":slugorfilename/"
  pages = ":filename/"

[params]
  logo = '/assets/favicon.ico'
  description = "Website and blog of Maarten Steenhagen"
  author = "Maarten Steenhagen"
  email = "maarten@steenhagen.nl"


  [params.comments]
    githubRepo = 'msteenhagen/indoxicate'
    theme = 'github-light'

  [params.podcast]
    description = "Short reflections on philosophy, society, and the dreadful state of the world"
    tagline = "Short reflections"
    download_url = "https://provo.lol/storage/audio/"
    cdn_url = "https://indoxicate.me"
    itunes_url = "https://podcasts.apple.com/us/podcast/indoxicate/id1667175259"
    itunes_id = "id0000000000"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/atom.xml"
    weight = -50
  [[menu.main]]
    identifier = "rss"
    name = "Newsletter"
    url = "http://eepurl.com/idUvuf"
    weight = 20



[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON", "mp3feed"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[outputFormats.mp3feed]
    MediaType = "application/rss+xml"
    BaseName = "index"
    path = "/feed/mp3"
    IsHTML = false
    IsPlainText = true
    noUgly = true
    Rel = "alternate"

ignoreErrors = ["error-remote-getjson"]
