baseURL = 'indoxicate.me'
languageCode = 'en-us'
title = 'Indoxicate'
paginate = 3
theme = 'maverick'


[permalinks]
  posts = ":slugorfilename/"
  pages = ":filename/"

[params]
  logo = '/assets/favicon.ico'
  description = "Website and blog of Maarten Steenhagen"
  author = "Maarten Steenhagen"


  [params.comments]
    githubRepo = 'msteenhagen/indoxicate'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/atom.xml"
    weight = -50
  [[menu.main]]
    identifier = "rss"
    name = "Newsletter"
    url = "http://eepurl.com/idUvuf"
    weight = 20



[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
